### ISSUE TITLE
Malware in scrypt-shim dependency used here. 

### ISSUE THREAD

**Issue by Faouzijedidi1** [traderjoe-xyz/joe-sdk#26]
## Security Threat

In the current verison of  Trader Joe sdk there is a dependency called `@openzeppelin/cli@2.8.2` which is no longer being developed and needs to be upgraded urgently. The reason is that it has dependencies that result in the installation of `scrypt-shim@github:web3-js/scrypt-shim` . This package   contains malicious code and presents a high risk security threat and should be removed as soon as possible. 
[scrypt-shim](https://www.npmjs.com/package/scrypt-shim) : npmjs has flagged this as well.

**Comment by gaepsuni** [comment]
Addressed in this PR https://github.com/traderjoe-xyz/joe-sdk/pull/40
